name: CI

on: 
  push:
  pull_request:

jobs:
  build-static-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update -qq
      - run: sudo apt-get install -qq nasm make gcc
      - run: make clean
      - run: make USE_CPP=No STATIC=yes -j$(nproc)
      - name: Check for C++ symbols
        run: |
          nm libopenh264.a | grep __gxx && echo "❌ Still has C++ symbols!" && exit 1 || echo "✅ No C++ symbols."
      - name: Upload static library
        uses: actions/upload-artifact@v4
        with:
          name: openh264-linux-static
          path: libopenh264.a

